### ISSUE TITLE
0.5.0dev Release

### ISSUE THREAD

**Issue by a-r-j** [BioPandas/biopandas#120]
Hey @rasbt, can we get a dev release? I think we're good to go with the recent PRs.

FWIW, it might be worth setting up a GitHub actions workflow to push to PyPI triggers by making a new release.

**Comment by rasbt** [comment]
Sounds good @a-r-j , I can push the dev version to PyPI now. Let me revisit the GitHub action for PyPI later (I would have to read into this first -- unless you have some template code that I could use)
